"""``krewlyzer_all_docs.md`` must match ``docs/``.

It is a single-file concatenation of the whole documentation tree, and it was
maintained by hand. It had drifted the way everything hand-copied in this repo
drifts: four documents missing — including ``docs/reference/output-files.md``,
which describes every output table — two listed that had been deleted, and
content predating several output changes.

Nothing referenced it, so nothing noticed. It is now generated by
``scripts/build_all_docs.py``; this makes forgetting to regenerate it a test
failure instead of a slow rot.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_SCRIPT = _ROOT / "scripts" / "build_all_docs.py"


def _load():
    """Import by path; ``scripts/`` is not a package."""
    spec = importlib.util.spec_from_file_location("build_all_docs", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_all_docs"] = module
    spec.loader.exec_module(module)
    return module


bad = _load()


def test_the_aggregate_is_up_to_date():
    """The check the release depends on.

    Deliberately compares the whole rendered text rather than a hash of the
    file list: a doc whose *contents* changed is exactly the case that used to
    slip through, and a filename-only check would still pass on it.
    """
    assert bad.main(["--check"]) == 0, (
        "krewlyzer_all_docs.md does not match docs/. Run:\n"
        "    python scripts/build_all_docs.py"
    )


def test_every_doc_is_included():
    """A structural cross-check, phrased as the question a reader would ask."""
    listed = {
        line[len("# FILE: ") :]
        for line in bad.OUTPUT.read_text().splitlines()
        if line.startswith("# FILE: ")
    }
    on_disk = {p.relative_to(_ROOT).as_posix() for p in bad.source_files()}
    assert listed == on_disk, (
        f"missing from the aggregate: {sorted(on_disk - listed)}; "
        f"listed but absent from docs/: {sorted(listed - on_disk)}"
    )


def test_output_is_deterministic():
    """Two renders must agree, or the file churns on every regeneration.

    `rglob` order is filesystem-dependent, so the sort in `source_files` is
    load-bearing rather than cosmetic.
    """
    assert bad.render(bad.source_files()) == bad.render(bad.source_files())
    paths = [p.relative_to(_ROOT).as_posix() for p in bad.source_files()]
    assert paths == sorted(paths), "source order is not stable"


def test_the_banner_warns_against_hand_editing():
    """The file was hand-maintained for a year; the next person needs telling."""
    head = bad.OUTPUT.read_text()[:400]
    assert "DO NOT EDIT" in head
    assert "scripts/build_all_docs.py" in head


def test_an_empty_docs_tree_is_an_error_not_a_truncation(tmp_path, monkeypatch):
    """Guards the failure mode that would silently blank the file.

    If `docs/` were moved or misresolved, rendering nothing and writing it out
    would replace 11k lines with a banner and exit 0.
    """
    monkeypatch.setattr(bad, "DOCS_DIR", tmp_path / "docs")
    (tmp_path / "docs").mkdir()
    assert bad.main([]) == 2, "an empty docs tree must fail, not truncate"


@pytest.mark.parametrize("doc", ["reference/output-files.md", "features/core/fsc.md"])
def test_key_reference_docs_are_present(doc):
    """`output-files.md` was the one actually missing, so name it explicitly."""
    assert f"# FILE: docs/{doc}" in bad.OUTPUT.read_text()
